### ISSUE TITLE
Issue using AuditUiBundle

### ISSUE THREAD

**Issue by iraldoad** [vouchedfor/AuditBundle#1]
**Unknown Entity namespace alias 'DataDogAuditBundle'.**
This error gives me after installing and configuring the bundle as the documentation indicates.

**Comment by jonathanstidwillvf** [comment]
The documentation did specify that it's assumed you already have added 'new DataDog\AuditBundle\DataDogAuditBundle(),' to AppKernel.php.  This should fix your issue.  I've updated the documentation to clarify this

**Comment by iraldoad** [comment]
Ok, thanks for the clarification. Everything works great!
