### ISSUE TITLE
Error when I use MySQL 5.7.14 in Windows

### ISSUE THREAD

**Issue by iraldoad** [vouchedfor/AuditBundle#2]
Can you tell me if it is a bundle error or mine?
-
An exception occurred while executing 'SELECT a.id, a.action, a.tbl, a.logged_at, u.username FROM audit_logs a INNER JOIN audit_associations au
ON(au.id=a.source_id) INNER JOIN usuario u ON(u.id=CAST(au.fk as NUMERIC)) ORDER BY logged_at DESC LIMIT 20':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NUMERIC)) ORDER BY logged_at DESC LIMIT 20' at line 2

**Comment by vouchedfor-admin** [comment]
It looks like an error on your end. You can't CAST as NUMERIC - only something like 'UNSIGNED'.  See https://www.techonthenet.com/mysql/functions/cast.php

**Comment by iraldoad** [comment]
Ok, thanks, I found the error. It is in an external code of another developer.
